### ISSUE TITLE
InvalidRequestError: Invalid URL (POST /chat/completions)

### ISSUE THREAD

**Issue by we1l1n** [beidongjiedeguang/openai-forward#10]
postman请求ok，但是用api
openai.api_base = "http://ip地址:9999"

返回InvalidRequestError: Invalid URL (POST /chat/completions)，求助！

**Comment by we1l1n** [comment]
@beidongjiedeguang 感谢大神！

**Comment by zddllc** [comment]
成功启动，没有问题，但是在浏览器里访问 http://0.0.0.0:9999/ 或者 http://0.0.0.0:9999/v1/chat/completions
就是出现这个错误，请问是什么情况，大神求助！应该不会仅局限在有公网ip的机器吧。

Traceback (most recent call last):

  File "/home/user/anaconda3/envs/py39/bin/openai_forward", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f8353162a60>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/__main__.py", line 21, in main
    fire.Fire(Cli)
    │    │    └ <class 'openai_forward.__main__.Cli'>
    │    └ <function Fire at 0x7f8352fb25e0>
    └ <module 'fire' from '/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/__init__.py'>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'openai_forward'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      │     │          └ ['run', '--port=9999', '--workers=1']
                      │     └ <class 'openai_forward.__main__.Cli'>
                      └ <function _Fire at 0x7f8352814a60>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f8352814b80>
    └ <function Cli.run at 0x7f8352fb2550>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ [9999, 1]
                └ <function Cli.run at 0x7f8352fb2550>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/__main__.py", line 9, in run
    uvicorn.run(
    │       └ <function run at 0x7f83524bac10>
    └ <module 'uvicorn' from '/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/__init__.py'>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7f83524ba670>
    └ <uvicorn.server.Server object at 0x7f83524159a0>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f83524ba700>
           │       │   └ <uvicorn.server.Server object at 0x7f83524159a0>
           │       └ <function run at 0x7f835292adc0>
           └ <module 'asyncio' from '/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/__init__.py'>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8352481b40>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f835292c820>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f835292c790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f835292e310>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f83529f5790>
    └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
> File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f83523ef970>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x7f8352415550>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f83523ef970>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f83510f0580>
          └ <fastapi.applications.FastAPI object at 0x7f8352415550>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f8351109310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x7f83510f0520>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f83510f0580>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f8351109310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f83510f04f0>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x7f83510f0520>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f835084e310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f83510f0460>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f83510f04f0>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f835084e310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x7f835236d190>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f83510f0460>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f835084e310>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │     └ <function Route.handle at 0x7f83518d48b0>
          └ Route(path='/{api_path:path}', name='reverse_proxy', methods=['DELETE', 'GET', 'HEAD', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'TR...
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f835084e310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f83507da0d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9999), 'cl...
          │    └ <function request_response.<locals>.app at 0x7f83510d45e0>
          └ Route(path='/{api_path:path}', name='reverse_proxy', methods=['DELETE', 'GET', 'HEAD', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'TR...
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f8350891e20>
                     └ <bound method Openai.reverse_proxy of <openai_forward.openai.Openai object at 0x7f83510db820>>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/openai.py", line 19, in reverse_proxy
    return await self._reverse_proxy(request)
                 │    │              └ <starlette.requests.Request object at 0x7f8350891e20>
                 │    └ <classmethod object at 0x7f835236da00>
                 └ <openai_forward.openai.Openai object at 0x7f83510db820>
  File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/_base.py", line 82, in _reverse_proxy
    req = client.build_request(
          │      └ <function BaseClient.build_request at 0x7f835144ea60>
          └ <httpx.AsyncClient object at 0x7f83510f05b0>

TypeError: build_request() got an unexpected keyword argument 'timeout'
