### ISSUE TITLE
[乱码] 在gitpod运行出现乱码

### ISSUE THREAD

**Issue by liqiujiong** [beidongjiedeguang/openai-forward#21]
使用gitpod，pip install openai-forward，运行后出现乱码。
![image](https://user-images.githubusercontent.com/5794205/237010440-8c5351bf-738d-4ba5-9180-058a8eb012e6.png)
![image](https://user-images.githubusercontent.com/5794205/237010479-ce811654-212f-4c6a-95e2-91153b2a2fd8.png)

**Comment by liqiujiong** [comment]
跟客户端有关，我切换到一台US的机器上运行。浏览器打开正常，但是poetman请求的话，就乱码了
![image](https://user-images.githubusercontent.com/5794205/237015334-f61c7e5c-69b2-4dd0-9721-8b592071efd8.png)
![image](https://user-images.githubusercontent.com/5794205/237015404-ea9f49b8-346f-4794-a06d-80394a55d44c.png)

**Comment by liqiujiong** [comment]
![image](https://user-images.githubusercontent.com/5794205/237015756-13bc2b98-63fd-4302-8625-3d9b822bba29.png)

**Comment by beidongjiedeguang** [comment]
嗯，确实有这个问题，似乎和系统环境相关； 我后面有时间把这个问题修掉。
目前建议暂时使用docker部署吧
@liqiujiong

**Comment by beidongjiedeguang** [comment]
#27 版本已修复
