### ISSUE TITLE
Render部署的时候，想开启不停机，健康检测设置/doc，请求失败

### ISSUE THREAD

**Issue by Kingbinary1** [beidongjiedeguang/openai-forward#37]
"GET /doc HTTP/1.1" 404 Not Found

**Comment by beidongjiedeguang** [comment]
这里是文档写错了，监控检测路径应该为 `/docs` ， 我后面会更正文档，多谢指出。    
另外，这里的零停机部署是指如果服务运行时挂掉了，服务会自动重新部署。而如果你希望的是让它15分钟之后不休眠，可以使用定时脚本（如每隔10分钟）发送请求进行保活就可以了。

**Comment by Kingbinary1** [comment]
好的，感谢！
