### ISSUE TITLE
CloudFlare Pages 部署后 Forward_key 无效，但转发有效。

### ISSUE THREAD

**Issue by zj1123581321** [beidongjiedeguang/openai-forward#39]
我使用 CloudFlare Pages 部署，环境变量配置如下
![image](https://github.com/beidongjiedeguang/openai-forward/assets/33171229/e6bdcdd6-c7e7-4a9d-ad89-10993243c8e8)

使用 Forward key 发送请求后返回值：
{
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
但使用 Openai 的官方 key 则正常返回。

在 cf 的配置指南里您提到：
> 这种部署方式轻便简洁，支持流式转发. 对于没有vps的用户还是十分推荐的。不过目前[_worker.js](https://github.com/beidongjiedeguang/openai-forward/blob/main/_worker.js)这个简单脚本仅提供转发服务, 不提供额外功能。

想确认一下使用 pages 部署也只是仅有转发功能吗？

**Comment by beidongjiedeguang** [comment]
hi @zj1123581321  
是的，cloudflare 部署方式仅有转发功能，如果希望使用forward-key等额外功能，可以参考 render 之类的基于云平台的部署方式，并且除了文档中列出的那几个云平台，其它平台如果支持Docker部署也将是适用的。
