### ISSUE TITLE
希望增加偽裝網頁

### ISSUE THREAD

**Issue by mmwong1984** [beidongjiedeguang/openai-forward#44]
例如當開網頁時會跳轉谷歌，而api就正常。看到其他api都可以

**Comment by beidongjiedeguang** [comment]
如果希望首页的`/`路由为自定义内容，可以使用nginx等转发工具去覆盖。并且`openai-forward`也提供了[转发路由前缀](https://github.com/beidongjiedeguang/openai-forward#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE%E9%A1%B9)的选项。
