### ISSUE TITLE
为什么这里要丢弃原始的请求头？

### ISSUE THREAD

**Issue by Karl-Sparticle** [beidongjiedeguang/openai-forward#45]
作者大大，请问为什么这里要丢弃原始的请求头呀？
![image](https://github.com/beidongjiedeguang/openai-forward/assets/95554023/e0c27bf0-2059-484d-b01d-4e689313d62d)

**Comment by beidongjiedeguang** [comment]
Hi,  
1. 因为用户在某些环境下请求时的请求头中的内容会导致结果乱码，参考 #21 
2. openai 的api接口header通常只接受`Content-Type`和`Authorization`两个字段（如看到有额外请求头的场景欢迎反馈）
