### ISSUE TITLE
好像无论stream设置成True/False，反向代理都是返回StreamResponse？

### ISSUE THREAD

**Issue by scriptboy1990** [beidongjiedeguang/openai-forward#64]
这块能实现成和openai api一样的逻辑吗，stream = True的时候，就流式返回，False的时候，就直接JsonResponse。

**Comment by beidongjiedeguang** [comment]
StreamResponse应该是兼容流式与非流式的，如果你发现某些情况下存在问题欢迎反馈

**Comment by scriptboy1990** [comment]
> StreamResponse应是兼容流式与非流式的，如果你发现某些情况下存在问题欢迎反馈

确实，我发现是兼容的。
