### ISSUE TITLE
请问docker部署如何设置进程数啊

### ISSUE THREAD

**Issue by seetimee** [beidongjiedeguang/openai-forward#66]

**Comment by beidongjiedeguang** [comment]
可以参考[docker-compose.yaml](https://github.com/beidongjiedeguang/openai-forward/blob/main/docker-compose.yaml)  
也可以直接 `docker run -d beidongjiedeguang/openai-forward:latest --workers=2`

**Comment by seetimee** [comment]
感谢感谢
