### ISSUE TITLE
希望添加自动禁用无效key

### ISSUE THREAD

**Issue by gougui** [beidongjiedeguang/openai-forward#67]
作者你好！如果能添加自动禁用无效key就太好了，例如429无余额、401封号的key。再问下，这个key最多可以输入多少个呢？

**Comment by beidongjiedeguang** [comment]
你好 @gougui ，
1. 这个功能的意义不明，我理解正常情况下应不会有太多无效的key。
2. OPENAI_API_KEY可以接受任意多个key输入。

**Comment by gougui** [comment]
> 你好 @gougui ，
> 
> 1. 这个功能的意义不明，我理解正常情况下应不会有太多无效的key。
> 2. OPENAI_API_KEY可以接受任意多个key输入。

1.如果遇到key无余额或者封号了只会报错不知道具体是哪个，添加自动禁用可能要涉及数据库有点复杂，可以考虑加个日志打印一部分key字段吗？比如失败了，日志打印出key的前25位，这样好手动删除已经无效的key
2.我添加200多个时会报列表太长，导致失败

**Comment by beidongjiedeguang** [comment]
https://github.com/beidongjiedeguang/openai-forward/blob/adebb24f9c39eed98a0d781073f003a54e04a585/openai_forward/forwarding/base.py#L320-L322
可以在这里321行处添加对不同的`r.status_code`的判断和相应的log 。  
第二个问题可能是由于环境变量储存上限(4KB)导致的，后面可能需要支持其它读取配置的方式（如.toml）多谢反馈
