### ISSUE TITLE
自动重试机制

### ISSUE THREAD

**Issue by gougui** [beidongjiedeguang/openai-forward#74]
自动重试机制：在请求失败时自动重试
作者麻烦问下，目前是哪些情况下会自动重试呢？能否加个配置参数自定一些错误码时自动重试呢？比如配置429，多个key时，一个key429频率超了会自动重试调用其它key

**Comment by gougui** [comment]
我自己魔改了下，好像重试还是用的原来的key，导致重试一样失败

**Comment by beidongjiedeguang** [comment]
目前的自动重试机制是用于请求时网络、并发等因素导致的错误，而不是用于判断返回的结果是否有错误。

**Comment by beidongjiedeguang** [comment]
对于你的需求可以参考这里的回答 https://github.com/beidongjiedeguang/openai-forward/issues/67#issuecomment-1696878845 ，可以通过判断返回的状态码确定是否重新请求。  
本项目不会额外开发这个需求。
